### ISSUE TITLE
The plugin sends frequent console.log messages and creates a large amount of clutter

### ISSUE THREAD

**Issue by DamnedScholar** [aidenlx/folder-note-core#10]
Since I've been using this plugin, I've been noticing a series of mysterious console messages that increased in volume the more notes I made. Here's an abbreviated screenshot:

https://i.imgur.com/2wGIgfX.png

I traced them back to [the folder note detection code](https://github.com/aidenlx/folder-note-core/blob/master/src/modules/resolver.ts#L37-L91), which seems to have no function aside from making noise for every folder that has notes with no folder note. I like the functionality of the package, but I feel like it should be quiet when encountering a folder that hasn't been set up yet. Since `folder-note-core` uses [`loglevel`](https://github.com/pimterry/loglevel#documentation) for logging, it wouldn't be hard to add a conditional at the top of the function that turns the logging on or off based on a setting.

**Comment by aidenlx** [comment]
by default, it shouldn't output to console... which log level does you set at the debug section of folder note setting tab?

**Comment by DamnedScholar** [comment]
Okay, maybe I touched that setting once weeks ago and didn't notice. It was on `TRACE`. Thanks for the RTFM. It's not spammy any more. 😬
