### ISSUE TITLE
Plugin failure: folder-note-core TypeError: a is not a constructor

### ISSUE THREAD

**Issue by farling42** [aidenlx/folder-note-core#11]
When I try to enable "Folder Note Core", I get the following error in the console log.

app.js:1 Plugin failure: folder-note-core TypeError: a is not a constructor
    at t.<anonymous> (app.js:1)
    at app.js:1
    at Object.next (app.js:1)
    at s (app.js:1)

**Comment by anselmwang** [comment]
It also failed on my computer.  Release 1.3.1 works fine.

# Environment
Obsidian version: v0.13.23
Plugin version: 1.3.2
OS: Windows 10

**Comment by EKliptus** [comment]
Same problem with obsidian v0.13.23 too

**Comment by LoneFireBlossom** [comment]
same

**Comment by aidenlx** [comment]
sorry, I've accidentally pushed a changes that will only be fixed in obsidian insider v0.13.24+, I've push [v1.3.3](https://github.com/aidenlx/folder-note-core/releases/tag/1.3.3) which should solve this issue for now.

**Comment by JuergenKaettnis** [comment]
Installed the new version. Then I cannot open files anymore. The page title remains and shows "no file". The usual menu for creating a new file, or choosing a recent opened, and so on does not appear anymore when it would be expected to appear. After turning off folder core plugin and Aiden's Folder Note plugin everything works normally again. I am on a Samsung S4 Tablet with Android.

**Comment by aidenlx** [comment]
> Installed the new version. Then I cannot open files anymore. The page title remains and shows "no file". The usual menu for creating a new file, or choosing a recent opened, and so on does not appear anymore when it would be expected to appear. After turning off folder core plugin and Aiden's Folder Note plugin everything works normally again. I am on a Samsung S4 Tablet with Android.

@HammyHavoc weird, I didn’t make any changes around panes… does disabling folder note alone and keep folder note core open make any difference? Can you open a new vault on mobile and install these two plugin to see if it still occurs?

**Comment by JuergenKaettnis** [comment]
Yeah, but now it starts to get really weird. I am sure that I turned off your plugins (both) and I went for a walk. Now I come back home and got your message. Though I went to turn on your plugins to experiment, but they were on already. And now I can not replicate this error again. Probably my tablet is sometimes possessed by an evil ghost. I was really quite sure it were your great plugins that never made any trouble before. But now I see ghosts... Continue to observe my ghosts. Not quite sure how to categorize this post; maybe "ghost bug". An other possibility could be that I got updates from other plugins and that changed something. I have more than 40 plugins installed, but not all activated. Thank's for the quick response. If I'll see other ghosts I might tell you (if they are funny enough). And thanks for the plugin.

**Comment by HammyHavoc** [comment]
Did you accidentally tag me? :-  )

**Comment by aidenlx** [comment]
yeah just notice 😂 sorry for tagging the wrong person

**Comment by sunsoy** [comment]
@Hansilein00726 I am also on tab S4, excalidraw doesn't launch any drawing view, page stays empty. I have fiddled for a long time, have you had any luck/fixes? I don't know where to start with error logs/info dump for troubleshooting. I hope one day it works and I can leave OneNote forever..
