### ISSUE TITLE
"Failed to load plugin"

### ISSUE THREAD

**Issue by JuergenKaettnis** [aidenlx/folder-note-core#12]
Suddenly unable to load plugin. Has there been an update? Get the above message.

**Comment by EKliptus** [comment]
> Suddenly unable to load plugin. Has there been an update? Get the above message.

Same problem with obsidian v0.13.23
I think this issue is the same as https://github.com/aidenlx/folder-note-core/issues/11

**Comment by aidenlx** [comment]
duplicate of #11
