### ISSUE TITLE
Bug: "Make Doc Folder Note" and "Link to Parent Folder" does not update links

### ISSUE THREAD

**Issue by anselmwang** [aidenlx/folder-note-core#13]
Let me describe each bug separately.

# "Make Doc Folder Note" does not update link
Suppose my directory structure is:
- temp
  - target.md
  - test.md

In `test.md`, I have a link `[[temp/target]]`. Once I execute "Make Doc Folder Note" on `target.md`, the link in `test.md` should be updated to `[[temp/target/target]]`.

# "Link to Parent Folder" does not update link
Suppose my directory structure is:
- temp
  - target
    - abc.md
   - test.md

In `test.md`, I have a link `[[temp/target/abc]]`. Once I execute "Link to Parent Folder" on `abc.md`, the link in `test.md` should be updated to `[[temp/target/target]]`.

**Comment by aidenlx** [comment]
merged and fixed in [v1.3.4](https://github.com/aidenlx/folder-note-core/releases/tag/1.3.4)
