### ISSUE TITLE
Bug: Right-Clicking on a folder with a folder note opens the folder note

### ISSUE THREAD

**Issue by metruzanca** [aidenlx/folder-note-core#6]
As per title right-Clicking on a folder with a folder note opens the folder note along side the context menu. This is nothing feature breaking but is quite annoying if you want to perform an action on the folder but not open the folder note. e.g. Create file inside folder

**Comment by aidenlx** [comment]
should be fixed in [folder-note-core v1.3.1](https://github.com/aidenlx/folder-note-core/releases/tag/1.3.1)
